project:
  type: website
  output-dir: ../docs

website:
  title: |
    It's Storytime!
  navbar:
    background: "#FF4500"
    left:
      - text: Main
        href: index.qmd
      - text: Code and Data
        href: secondary/code-and-data.qmd
      - text: Authors
        href: secondary/authors.qmd           
      - text: References
        href: secondary/references.qmd      
  page-footer:
    left: |
      A project by {{< var author.name >}}.
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

  sidebar:
    style: "docked"
    collapse-level: 2
    align: left
    contents:
      - index.qmd
      - section: "EDA"
        contents:
          - eda/topics.qmd
          - eda/exploratory.qmd
      #- eda.qmd
      - nlp.qmd
      - ml.qmd
      - summary.qmd


format:
  html:
    theme: united
    css: styles.css
    toc: true
    link-external-newwindow: true

bibliography: references.bib

